import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className=''>
        <Link href='/'>Home</Link>
        <Link href={'/about'}>About</Link>
      </nav>
      <main className={styles.main}>

        <div className={styles.description}>
        <h1>About us</h1>
        </div>
      </main>
    </>
  )
}
